version: 0.2

phases:
  pre_build:
    commands:
    - export CI_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')

  build:
    commands:
      - make build

  post_build:
    commands:
      - >-
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ]; then
            exit 1;
        fi
      - make push
