version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - export REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export IMAGE_VERSION=$(git describe --always --tag)
      - docker build --pull -t $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_VERSION .

  post_build:
    commands:
      - >-
        if [ "$CODEBUILD_BUILD_SUCCEEDING" = "0" ]; then
            exit 1;
        fi
      - docker push $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_VERSION
